name: Docker Image CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

         name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: 3.10.11


        - name: Get pip cache dir
          id: pip-cache
          run: |
            echo "::set-output name=dir::$(pip cache dir)"

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ${{ steps.pip-cache.outputs.dir }}
            key: ${{ matrix.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ matrix.os }}-pip-${{ hashFiles('**/requirements.txt') }}


        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements_dev.txt

        - uses: iterative/setup-dvc@v1
        - name: Get data
          run: dvc pull
          env:
              GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        - name: Build the Docker image
          run: |
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
                -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
            docker build . --file dockerfiles/trainer_ci.dockerfile \
                --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
            docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
